spring:
  application:
    name: dream_stadium

  datasource :
    url: jdbc:mysql://localhost:3307/dream_stadium
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  data:
    redis:
      host: localhost
      port: 6379

      #이렇게만 설정하면 Redisson이 자동으로 RedissonClient 빈을 만들어 분산락에서 사용 가능
      #RedisConfig 클래스는 필요 없음.


